name: flock
description: "A new Flutter project."

publish_to: 'none' 

version: 20.1.5+116


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  shared_preferences: ^2.5.2
  fluttertoast: ^9.0.0
  qr_flutter: ^4.1.0
  http: ^1.2.0
  permission_handler: ^12.0.1
  api_request: ^1.0.0-pre-8
  multiselect: ^0.1.1
  image_picker: ^1.1.2
  lottie: ^3.3.1
  provider: ^6.1.2
  google_maps_flutter: ^2.11.0
  multi_select_flutter: ^4.1.3
  geolocator: ^14.0.2
  dio: ^5.8.0+1
  multiselect_formfield: ^0.1.7
  mobile_scanner: ^7.1.3
  dropdown_search: ^6.0.2
  flutter_image_compress: ^2.2.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^19.5.0

  geocoding: ^4.0.0
  webview_flutter: ^4.10.0
  sqflite_darwin: ^2.4.2
  permission_handler_apple: ^9.4.6
  flutter_html: ^3.0.0
  timezone: ^0.10.1
  file_picker: ^10.0.0
  flutter_multi_select_items: ^0.4.3
  video_player: ^2.9.5
  chewie: ^1.7.4
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3
  keyboard_actions: ^4.2.0
  workmanager: ^0.9.0+3
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  intl: ^0.20.0
 
  flutter_branch_sdk: ^8.5.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^6.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_upd.png"
  adaptive_icon_foreground: "assets/logo_upd.png"
  adaptive_icon_background: "#FFFFFF" 
  remove_alpha_ios: true


flutter:
  assets:
    - assets/bird.png
    - assets/tutorials.png
    - assets/login_back.jpg
    - assets/business_checkin.png
    - assets/business_eggs.png
    - assets/statistics.png
    - assets/view.png
    - assets/side_arrow.png
    - assets/scan_qr.png
    - assets/orange_hotel.png
    - assets/business_logo.png
    - assets/bottom_bird.png
    - assets/profile.png
    - assets/people.png
    - assets/back.png
    - assets/back.png
    - assets/back_updated.png
    - assets/location.png
    - assets/camera.png
    - assets/bottom_nav.png
    - assets/edit.png
    - assets/points.png
    - assets/notify.png
    - assets/business_dashboard.png
    # - assets/Nav_Bg.png
    - assets/nav.png
    - assets/Bird_Full_Eye_Blinking.gif
    - assets/edit.png
    - assets/closebtn.png
    - assets/camera.png
    - assets/date_time.png
    - assets/request.png
    - assets/Background.jpg
   
    - assets/drop_up.png
    - assets/back.png
    - assets/drop_down.png
    - assets/bottom_nav_dark.png
    



  
    - assets/points.png
    - assets/feather.png

  uses-material-design: true

  